export enum ActionType  {
    BALANCE_DEPOSIT = "BALANCE_DEPOSIT",
    BALANCE_WITHDRAW = "BALANCE_WITHDRAW",
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    REGISTER_REQ = "REGISTER_REQUEST",
    REGISTER_SUC = "REGISTER_SUCCESS",
    REGISTER_FAIL = "REGISTER_FAILURE",
}