export enum ActionType  {
    DEPOSIT = "BALANCE_DEPOSIT",
    WITHDRAW = "BALANCE_WITHDRAW",
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE"
}